#!/bin/bash
echo "Testing interactive mode..."
echo ""
echo "When you run: python rag_semantic.py"
echo ""
echo "You will see:"
echo "1. API key prompt (or auto-load from env)"
echo "2. Model choice (1 or 2)"
echo "3. Menu with 10 questions + option 0"
echo "4. You type a number (1-10) or 0"
echo "5. If 0, you type your custom question"
echo "6. System answers"
echo "7. Press Enter to continue"
echo "8. Menu appears again"
echo ""
echo "To test manually, run:"
echo "  python rag_semantic.py"
echo ""
echo "Then try:"
echo "  - Type '1' to ask about Chinggis Khan"
echo "  - Type '4' to ask about Khunnu"
echo "  - Type '0' then enter custom question"
echo "  - Type 'exit' to quit"
